### ISSUE TITLE
postToChat can't concatenate

### ISSUE THREAD

**Issue by jrobinson-uk** [raspberrypilearning/minecraft-photobooth#11]
In the section : 

```
while True:
    x, y, z, = mc.player.getPos()
    mc.postToChat(x, y, z)
```

postToChat throws an error as it can't concatenate these values.
Should this be:
`print(x,y,z)`

or 

`mc.postToChat("{} , {}, {}".format(x,y,z))`

**Comment by jrobinson-uk** [comment]
or 

``` python
mc.postToChat((x, y, z))
```

**Comment by bennuttall** [comment]
If `mc.postToChat((x, y, z))` works I'd go for that - could you push a fix?

Thanks

**Comment by jrobinson-uk** [comment]
Done
