### ISSUE TITLE
Use getTilePos instead of getPos

### ISSUE THREAD

**Issue by SteveAmor** [raspberrypilearning/minecraft-photobooth#18]
@martinohanlon having run through this today at a Tech Jam, I think it would be better to try and use getTilePos.  I'm happy to do a PR if it's going to be of benefit.

I think it would be much better to have x, y & z equal to a position without decimal places and without using >= or <= as the other problem I came across today was that the x position was negative so we had to change x >= photobooth to x <= photobooth (ref https://projects.raspberrypi.org/en/projects/minecraft-photobooth/7)

**Comment by martinohanlon** [comment]
I am in 2 minds about this...

This is a developer level project (https://curriculum.raspberrypi.org/programming/developer/).

By simplifying do we make the challenge too easy?

Would it be better to include a hints section which expands on the following text and provide more advice relating to using conditions to detect you position?

```
You will note that the if statement checks if x value is greater than or equal to 10.5: this is ensure that it picks up the block as it could have a value of 10.6. Remember to replace the x, y, and z values with the values from your photobooth.
```

**Comment by SteveAmor** [comment]
Good point, I didn't realise that it was clasified as a developer level project.
The hint may also want to include that if the photobooth position has a negative x coordinate that the >= will need to change to <=

**Comment by martinohanlon** [comment]
Absolutely.

I will leave this issue open so it can be addressed in our maintenance and testing.

**Comment by martinohanlon** [comment]
Added some hints to step 7 to provide additional support.
