### ISSUE TITLE
Format checking

### ISSUE THREAD

**Issue by bennuttall** [raspberrypilearning/minecraft-photobooth#2]

**Comment by LornaLynch** [comment]
Is this up on staging anywhere, or am I OK to check in GitHub?

**Comment by LornaLynch** [comment]
Ignore the previous comment: I've been through this in the desktop client, made some copy editing/formatting changes, and I need to merge the pull request. GitHub won't let me do it myself for some reason. Once someone has merged it for me, I can give the resource another check though.

**Comment by bennuttall** [comment]
It's on staging at http://staging.raspberrypi.org/learning/minecraft-photobooth

**Comment by LornaLynch** [comment]
Thanks, I'll have a look after I've sorted out my mistake in the code.
